apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-obnrihmc
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-obnrihmc:363326f4c7ea2dabe4016638888dde6c383ad31b@sha256:680dcc38e63559fa571efb181e0e55a50753805554791faad874b20bf97ca1aa
        name: container-image  
